-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, '%H') AS 'HOUR', COUNT(DATETIME) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) > 8 AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
ORDER BY DATE_FORMAT(DATETIME, '%H')